//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

volatile const unsigned char BirdSprite [] PROGMEM = {
0x78, 0x84, 0x82, 0x81, 0xC9, 0x22, 0x24, 0x18, 
};
