//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char wall [] PROGMEM = {
0xFF, 0x81, 0x95, 0xA9, 0x89, 0xD1, 0x85, 0xFF, 
};
